### ISSUE TITLE
clerical error on line 487

### ISSUE THREAD

**Issue by Mikachu2333** [StardockCorp/Stardock-Software-Localization#59]
`msgid "Compatibility issue found..."` Should be `msgid "Compatibiliy issue found..."`

And, line 487 is similar to line 490
![图片](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/e0bed424-3fef-4f1f-b986-5296dd7364f1)

**Comment by Mikachu2333** [comment]
![图片](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/0ec9210c-89ed-4557-a9c0-ba4bd2268225)

**Comment by magnumpci** [comment]
I am a bit confused..

'Compatibiliy' is not an English word...

'Compatibility' is the correct spelling.

**Comment by Mikachu2333** [comment]
Oh, I don't know. Due to the annoying advertisements in Poedit, I directly translated the _.po file_ using vscode and noticed this strange spelling.

So, what should I translate this non-English word? (I am not proficient in languages other than Chinese and English)

**Comment by Mikachu2333** [comment]
> 'Compatibiliy' is not an English word...

I misunderstood "not an English word" as "a correct vocabulary in another language", so what you mean is that the "Compatibiliy" is wrong and should be corrected as "Compatibility"?
But this words appeared in the

**Comment by magnumpci** [comment]
I have not looked up that section, only your presented section.  

If it reads 'Compatibiliy', that would be wrong (not an English word)...

If it reads 'Compatibility', that would be correct.

**Comment by Mikachu2333** [comment]
ok, thanks!
