### ISSUE TITLE
Qusetion about this: "Please limit title length to 500 characters or less."

### ISSUE THREAD

**Issue by Mikachu2333** [StardockCorp/Stardock-Software-Localization#61]
What the "character" mean? 500 utf-8 character or 500 ancii character(250 utf-8)

**Comment by magnumpci** [comment]
Are you referring to something in a Stardock app or Github?

Sean Drohan
Stardock Product Lifecycle Manager

**Comment by Mikachu2333** [comment]
The space a  character of Chinese requires depending on the encoding the software and system use.

For example:
---

## C
As is known to all, if you use C or C + + language programming and using the traditional _char type_ to storage data, a Chinese character often requres _2/3\*sizeof(char) [2/3 bytes]_ space.

![02月08日15时51分26秒](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/de070558-3633-4668-8efe-cb63470d2aed)

![02月08日15时55分57秒](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/f3b5e76d-31a7-4582-a792-65bec4f5440b)

## Rust
Rust storgage every of its character with UTF8 encoding and Chinese characters use 3 bytes
![02月08日16时24分16秒](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/a3d1d517-4150-45db-aa9e-b75caa2c225d)

---

So, I wander if your team stroage String with UTF8 or GB2312 encoding and how should I translate it. 

500 chinese characters [500/1] (give each character 3bytes)
250 chinese characters [500/2] (give each character 2 bytes and use GB2312 encoding)
166 chinese characters [500/3] (treat each character as english letter and use UTF8 encoding)?

**Comment by Mikachu2333** [comment]
This question is about the languuage file of Fence5, line 1698.

![图片](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/6db07c5f-33ae-4d6d-bd3e-8231e80e3ad3)

**Comment by jeffbargmann** [comment]
Hi @Mikachu2333, the encoding system is the Windows/Win32 standard of UTF-16 (i.e. wide-char), so exactly 2 bytes per character. Excellent question, thank you!
