### ISSUE TITLE
Line 1921 "S&ort by"

### ISSUE THREAD

**Issue by Mikachu2333** [StardockCorp/Stardock-Software-Localization#62]
![01月24日18时14分25秒](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/9058e6f7-a7c9-44ba-bd37-92825e91b03a)

Couldn't understand it

**Comment by magnumpci** [comment]
The '&' there (if that is what you are referring to) means it is underlined in the UI, perhaps for 'ALT' key functionality.

**Comment by Mikachu2333** [comment]
Thanks for answering

**Comment by magnumpci** [comment]
Of course, thanks for your participation.
