### ISSUE TITLE
Some text boxes are too small and should be enlarged

### ISSUE THREAD

**Issue by Mikachu2333** [StardockCorp/Stardock-Software-Localization#63]
For example, the word "No" in Chinese means “否” (the antonym of correct) or “取消” (cancel), and there is no translation method (even if just use only a Chinese character) that can perfectly make users understand the meaning of the text when the length contains only two English letters. 

In addition, the height of Chinese characters is also higher than English characters, so many Chinese characters have been roughly truncated (cut) by the current text boxes.

![图片](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/aadc2e15-62e6-493b-8f9c-5f0380515efe)

**Comment by magnumpci** [comment]
> In addition, the height of Chinese characters is also higher than English characters, so many Chinese characters have been roughly truncated (cut) by the current text boxes.

Interesting.  Are there examples (screenshots) of Chinese characters being cut off in any Stardock software app UI (not games)?

Thanks for the feedback,

Sean Drohan
Stardock Product Lifecycle Manager

**Comment by Mikachu2333** [comment]
Yes, as the following pic shows.

BLUE:  Should be.
PINK:  Part of cut.
RED:   What Fences5 shows
Green: Some explainations about it.

![图片](https://github.com/StardockCorp/Stardock-Software-Localization/assets/63829496/4d10e7b8-a273-4a5f-b614-e5b7bb4aa23d)

**Comment by jeffbargmann** [comment]
@Mikachu2333 thank you for pointing this out! We're going to take a look. It sounds like we need to add some additional vertical padding. Which OS and DPI are you running, just to confirm? Looks like perhaps Windows 10, at regular 100% DPI?

**Comment by Mikachu2333** [comment]
Win10,22H2,150%,1920*1080
